version: "3"
services:
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  gateway:
    build: ./src/api-gateway
    ports:
      - "3000:3000"
  wallet:
    build: ./src/wallet-service
    depends_on:
      mongodb:
        condition: service_started